<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "achievement".
 *
 * @property string $id
 * @property string $user_id
 * @property string $achieve_date
 * @property string $achieve_desc
 * @property string $achieve_desc_en
 *
 * @property User $user
 */
class Achievement extends \yii\db\ActiveRecord
{
    public $month;
    public $year;

    public function beforeSave($insert)
    {
        $this->achieve_date = (new \DateTime($this->year . '-' . $this->month . '-' . '01'))->format('Y-m-d');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'achievement';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'achieve_desc'], 'required'],
            [['user_id'], 'integer'],
            [['achieve_desc', 'achieve_desc_en'], 'string'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['month', 'year'], 'safe'],
            [['month', 'year'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Сотрудник',
            'achieve_date' => 'Дата достижения',
            'achieve_desc' => 'Описание',
            'achieve_desc_en' => 'Achieve Desc En',
            'month' => 'Месяц',
            'year' => 'Год'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}
